# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(373, 753)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        Form.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.txt_user = QtWidgets.QLabel(Form)
        self.txt_user.setGeometry(QtCore.QRect(40, 110, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_user.setFont(font)
        self.txt_user.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_user.setObjectName("txt_user")
        self.btn_add_songs = QtWidgets.QPushButton(Form)
        self.btn_add_songs.setGeometry(QtCore.QRect(110, 670, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_add_songs.setFont(font)
        self.btn_add_songs.setObjectName("btn_add_songs")
        self.txt_auth_google = QtWidgets.QLabel(Form)
        self.txt_auth_google.setGeometry(QtCore.QRect(40, 230, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_auth_google.setFont(font)
        self.txt_auth_google.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_auth_google.setObjectName("txt_auth_google")
        self.txt_auth_spotify = QtWidgets.QLabel(Form)
        self.txt_auth_spotify.setGeometry(QtCore.QRect(40, 480, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_auth_spotify.setFont(font)
        self.txt_auth_spotify.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_auth_spotify.setObjectName("txt_auth_spotify")
        self.txt_google = QtWidgets.QLineEdit(Form)
        self.txt_google.setGeometry(QtCore.QRect(40, 300, 291, 41))
        self.txt_google.setObjectName("txt_google")
        self.txt_spotify = QtWidgets.QLineEdit(Form)
        self.txt_spotify.setGeometry(QtCore.QRect(40, 530, 291, 41))
        self.txt_spotify.setObjectName("txt_spotify")
        self.btn_link_google = QtWidgets.QPushButton(Form)
        self.btn_link_google.setGeometry(QtCore.QRect(40, 360, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_link_google.setFont(font)
        self.btn_link_google.setObjectName("btn_link_google")
        self.btn_autenticar_google = QtWidgets.QPushButton(Form)
        self.btn_autenticar_google.setGeometry(QtCore.QRect(190, 360, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_autenticar_google.setFont(font)
        self.btn_autenticar_google.setObjectName("btn_autenticar_google")
        self.btn_autenticar_spotify = QtWidgets.QPushButton(Form)
        self.btn_autenticar_spotify.setGeometry(QtCore.QRect(190, 590, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_autenticar_spotify.setFont(font)
        self.btn_autenticar_spotify.setObjectName("btn_autenticar_spotify")
        self.btn_link_spotify = QtWidgets.QPushButton(Form)
        self.btn_link_spotify.setGeometry(QtCore.QRect(40, 590, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_link_spotify.setFont(font)
        self.btn_link_spotify.setObjectName("btn_link_spotify")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.txt_user.setText(_translate("Form", "Favor Efetuar o Login"))
        self.btn_add_songs.setText(_translate("Form", "Buscar Músicas"))
        self.txt_auth_google.setText(_translate("Form", "Não Autenticado"))
        self.txt_auth_spotify.setText(_translate("Form", "Não Autenticado"))
        self.btn_link_google.setText(_translate("Form", "Link"))
        self.btn_autenticar_google.setText(_translate("Form", "Autenticar"))
        self.btn_autenticar_spotify.setText(_translate("Form", "Autenticar"))
        self.btn_link_spotify.setText(_translate("Form", "Link"))
